// Compiled shader for PC, Mac & Linux Standalone, uncompressed size: 23.1KB

Shader "GGXSSS_PlusTex_Trans" {
Properties {
 _Color ("Main Color", Color) = (1,1,1,1)
 _MainTex ("Base (RGB)", 2D) = "white" {}
 _Roughness ("Roughness", Range(0,1)) = 0.5
 _F0 ("F0", Range(0,1)) = 0.5
 _RimColor ("Rim Color", Color) = (1,1,1,1)
 _RimPower ("Rim Power", Range(0.1,30)) = 2
 _RimShift ("Rim Shift", Range(-1,1)) = 0
 _TranslucentColor ("Translucent Color", Color) = (1,1,1,1)
 _TranslucentPower ("Translucent Power", Range(0.1,10)) = 2
 _TranslucentTilt ("Translucent Tilt", Range(0,1)) = 0
 _SpecularColor ("Specular Color", Color) = (1,1,1,1)
 _Metalness ("Metalness", Range(0,1)) = 0
 _BumpMap ("Bump Map", 2D) = "bump" {}
 _BumpScale ("Bump Scale", Range(0,5)) = 1
 _SpecularMap ("Specular Map", 2D) = "white" {}
 _RoughnessMap ("Roughness Map", 2D) = "white" {}
 _RimMap ("Rim Map", 2D) = "white" {}
 _TranslucentMap ("Translucent Map", 2D) = "white" {}
 _FresnelMap ("Fresnel Map", 2D) = "white" {}
 _MetalnessMap ("Metalness Map", 2D) = "white" {}
 _AOMap ("AO Map", 2D) = "white" {}
}
SubShader { 
 LOD 200
 Tags { "QUEUE"="Transparent" "IGNOREPROJECTOR"="true" "RenderType"="Transparent" }


 // Stats for Vertex shader:
 //       d3d11 : 28 math
 //    d3d11_9x : 28 math
 // Stats for Fragment shader:
 //       d3d11 : 114 math, 12 texture, 4 branch
 Pass {
  Name "FORWARD"
  Tags { "LIGHTMODE"="ForwardBase" "QUEUE"="Transparent" "IGNOREPROJECTOR"="true" "RenderType"="Transparent" }
  ZWrite Off
  Cull Off
  Blend SrcAlpha OneMinusSrcAlpha
  AlphaTest Greater 0
Program "vp" {
// Platform opengl had shader errors
//   <no keywords>
// Platform d3d9 had shader errors
//   <no keywords>
SubProgram "d3d11 " {
// Stats: 28 math
Bind "vertex" Vertex
Bind "color" Color
Bind "normal" Normal
Bind "texcoord" TexCoord0
Bind "tangent" TexCoord2
ConstBuffer "$Globals" 400
Matrix 336 [_LightMatrix0]
ConstBuffer "UnityPerCamera" 128
Vector 64 [_WorldSpaceCameraPos] 3
ConstBuffer "UnityPerDraw" 336
Matrix 0 [glstate_matrix_mvp]
Matrix 192 [_Object2World]
BindCB  "$Globals" 0
BindCB  "UnityPerCamera" 1
BindCB  "UnityPerDraw" 2
"vs_4_0
eefiecedhglcjngbpffpkaobgmlaejflkiohejcpabaaaaaaheahaaaaadaaaaaa
cmaaaaaanmaaaaaameabaaaaejfdeheokiaaaaaaafaaaaaaaiaaaaaaiaaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapapaaaaijaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaapahaaaajbaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaa
ahahaaaajiaaaaaaaaaaaaaaaaaaaaaaadaaaaaaadaaaaaaapadaaaakbaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaaeaaaaaaapaaaaaafaepfdejfeejepeoaafeebeo
ehefeofeaaeoepfcenebemaafeeffiedepepfceeaaedepemepfcaaklepfdeheo
oaaaaaaaaiaaaaaaaiaaaaaamiaaaaaaaaaaaaaaabaaaaaaadaaaaaaaaaaaaaa
apaaaaaaneaaaaaaaaaaaaaaaaaaaaaaadaaaaaaabaaaaaaadamaaaaneaaaaaa
abaaaaaaaaaaaaaaadaaaaaaacaaaaaaahaiaaaaneaaaaaaacaaaaaaaaaaaaaa
adaaaaaaadaaaaaaapaaaaaaneaaaaaaadaaaaaaaaaaaaaaadaaaaaaaeaaaaaa
apaaaaaaneaaaaaaaeaaaaaaaaaaaaaaadaaaaaaafaaaaaaahaiaaaaneaaaaaa
afaaaaaaaaaaaaaaadaaaaaaagaaaaaaahaiaaaaneaaaaaaagaaaaaaaaaaaaaa
adaaaaaaahaaaaaaahaiaaaafdfgfpfaepfdejfeejepeoaafeeffiedepepfcee
aaklklklfdeieefckiafaaaaeaaaabaagkabaaaafjaaaaaeegiocaaaaaaaaaaa
bjaaaaaafjaaaaaeegiocaaaabaaaaaaafaaaaaafjaaaaaeegiocaaaacaaaaaa
baaaaaaafpaaaaadpcbabaaaaaaaaaaafpaaaaadhcbabaaaabaaaaaafpaaaaad
hcbabaaaacaaaaaafpaaaaaddcbabaaaadaaaaaaghaaaaaepccabaaaaaaaaaaa
abaaaaaagfaaaaaddccabaaaabaaaaaagfaaaaadhccabaaaacaaaaaagfaaaaad
pccabaaaadaaaaaagfaaaaadpccabaaaaeaaaaaagfaaaaadhccabaaaafaaaaaa
gfaaaaadhccabaaaagaaaaaagfaaaaadhccabaaaahaaaaaagiaaaaacadaaaaaa
diaaaaaipcaabaaaaaaaaaaafgbfbaaaaaaaaaaaegiocaaaacaaaaaaabaaaaaa
dcaaaaakpcaabaaaaaaaaaaaegiocaaaacaaaaaaaaaaaaaaagbabaaaaaaaaaaa
egaobaaaaaaaaaaadcaaaaakpcaabaaaaaaaaaaaegiocaaaacaaaaaaacaaaaaa
kgbkbaaaaaaaaaaaegaobaaaaaaaaaaadcaaaaakpccabaaaaaaaaaaaegiocaaa
acaaaaaaadaaaaaapgbpbaaaaaaaaaaaegaobaaaaaaaaaaadgaaaaafdccabaaa
abaaaaaaegbabaaaadaaaaaadiaaaaaihcaabaaaaaaaaaaafgbfbaaaaaaaaaaa
egiccaaaacaaaaaaanaaaaaadcaaaaakhcaabaaaaaaaaaaaegiccaaaacaaaaaa
amaaaaaaagbabaaaaaaaaaaaegacbaaaaaaaaaaadcaaaaakhcaabaaaaaaaaaaa
egiccaaaacaaaaaaaoaaaaaakgbkbaaaaaaaaaaaegacbaaaaaaaaaaadcaaaaak
hcaabaaaaaaaaaaaegiccaaaacaaaaaaapaaaaaapgbpbaaaaaaaaaaaegacbaaa
aaaaaaaaaaaaaaajhcaabaaaaaaaaaaaegacbaiaebaaaaaaaaaaaaaaegiccaaa
abaaaaaaaeaaaaaabaaaaaahicaabaaaaaaaaaaaegacbaaaaaaaaaaaegacbaaa
aaaaaaaaeeaaaaaficaabaaaaaaaaaaadkaabaaaaaaaaaaadiaaaaahhccabaaa
acaaaaaapgapbaaaaaaaaaaaegacbaaaaaaaaaaadiaaaaaipcaabaaaaaaaaaaa
fgbfbaaaaaaaaaaaegiocaaaacaaaaaaanaaaaaadcaaaaakpcaabaaaaaaaaaaa
egiocaaaacaaaaaaamaaaaaaagbabaaaaaaaaaaaegaobaaaaaaaaaaadcaaaaak
pcaabaaaaaaaaaaaegiocaaaacaaaaaaaoaaaaaakgbkbaaaaaaaaaaaegaobaaa
aaaaaaaadcaaaaakpcaabaaaaaaaaaaaegiocaaaacaaaaaaapaaaaaapgbpbaaa
aaaaaaaaegaobaaaaaaaaaaadgaaaaafpccabaaaadaaaaaaegaobaaaaaaaaaaa
diaaaaaipcaabaaaabaaaaaafgafbaaaaaaaaaaaegiocaaaaaaaaaaabgaaaaaa
dcaaaaakpcaabaaaabaaaaaaegiocaaaaaaaaaaabfaaaaaaagaabaaaaaaaaaaa
egaobaaaabaaaaaadcaaaaakpcaabaaaabaaaaaaegiocaaaaaaaaaaabhaaaaaa
kgakbaaaaaaaaaaaegaobaaaabaaaaaadcaaaaakpccabaaaaeaaaaaaegiocaaa
aaaaaaaabiaaaaaapgapbaaaaaaaaaaaegaobaaaabaaaaaadiaaaaaihcaabaaa
aaaaaaaafgbfbaaaacaaaaaacgijcaaaacaaaaaaanaaaaaadcaaaaakhcaabaaa
aaaaaaaacgijcaaaacaaaaaaamaaaaaaagbabaaaacaaaaaaegacbaaaaaaaaaaa
dcaaaaakhcaabaaaaaaaaaaacgijcaaaacaaaaaaaoaaaaaakgbkbaaaacaaaaaa
egacbaaaaaaaaaaadiaaaaaihcaabaaaabaaaaaafgbfbaaaabaaaaaajgiecaaa
acaaaaaaanaaaaaadcaaaaakhcaabaaaabaaaaaajgiecaaaacaaaaaaamaaaaaa
agbabaaaabaaaaaaegacbaaaabaaaaaadcaaaaakhcaabaaaabaaaaaajgiecaaa
acaaaaaaaoaaaaaakgbkbaaaabaaaaaaegacbaaaabaaaaaadiaaaaahhcaabaaa
acaaaaaaegacbaaaaaaaaaaaegacbaaaabaaaaaadcaaaaakhcaabaaaacaaaaaa
cgajbaaaaaaaaaaajgaebaaaabaaaaaaegacbaiaebaaaaaaacaaaaaadgaaaaaf
cccabaaaafaaaaaaakaabaaaacaaaaaadgaaaaafbccabaaaafaaaaaackaabaaa
abaaaaaadgaaaaafeccabaaaafaaaaaabkaabaaaaaaaaaaadgaaaaafbccabaaa
agaaaaaaakaabaaaabaaaaaadgaaaaafbccabaaaahaaaaaabkaabaaaabaaaaaa
dgaaaaafeccabaaaagaaaaaackaabaaaaaaaaaaadgaaaaafeccabaaaahaaaaaa
akaabaaaaaaaaaaadgaaaaafcccabaaaagaaaaaabkaabaaaacaaaaaadgaaaaaf
cccabaaaahaaaaaackaabaaaacaaaaaadoaaaaab"
}
SubProgram "d3d11_9x " {
// Stats: 28 math
Bind "vertex" Vertex
Bind "color" Color
Bind "normal" Normal
Bind "texcoord" TexCoord0
Bind "tangent" TexCoord2
ConstBuffer "$Globals" 400
Matrix 336 [_LightMatrix0]
ConstBuffer "UnityPerCamera" 128
Vector 64 [_WorldSpaceCameraPos] 3
ConstBuffer "UnityPerDraw" 336
Matrix 0 [glstate_matrix_mvp]
Matrix 192 [_Object2World]
BindCB  "$Globals" 0
BindCB  "UnityPerCamera" 1
BindCB  "UnityPerDraw" 2
"vs_4_0_level_9_1
eefieceddjacifpcdglbbflepmbllhikdfjjclhkabaaaaaaleakaaaaaeaaaaaa
daaaaaaagmadaaaabmajaaaammajaaaaebgpgodjdeadaaaadeadaaaaaaacpopp
nmacaaaafiaaaaaaaeaaceaaaaaafeaaaaaafeaaaaaaceaaabaafeaaaaaabfaa
aeaaabaaaaaaaaaaabaaaeaaabaaafaaaaaaaaaaacaaaaaaaeaaagaaaaaaaaaa
acaaamaaaeaaakaaaaaaaaaaaaaaaaaaaaacpoppbpaaaaacafaaaaiaaaaaapja
bpaaaaacafaaabiaabaaapjabpaaaaacafaaaciaacaaapjabpaaaaacafaaadia
adaaapjaafaaaaadaaaaahiaaaaaffjaalaaoekaaeaaaaaeaaaaahiaakaaoeka
aaaaaajaaaaaoeiaaeaaaaaeaaaaahiaamaaoekaaaaakkjaaaaaoeiaaeaaaaae
aaaaahiaanaaoekaaaaappjaaaaaoeiaacaaaaadaaaaahiaaaaaoeibafaaoeka
aiaaaaadaaaaaiiaaaaaoeiaaaaaoeiaahaaaaacaaaaaiiaaaaappiaafaaaaad
abaaahoaaaaappiaaaaaoeiaafaaaaadaaaaapiaaaaaffjaalaaoekaaeaaaaae
aaaaapiaakaaoekaaaaaaajaaaaaoeiaaeaaaaaeaaaaapiaamaaoekaaaaakkja
aaaaoeiaaeaaaaaeaaaaapiaanaaoekaaaaappjaaaaaoeiaafaaaaadabaaapia
aaaaffiaacaaoekaaeaaaaaeabaaapiaabaaoekaaaaaaaiaabaaoeiaaeaaaaae
abaaapiaadaaoekaaaaakkiaabaaoeiaaeaaaaaeadaaapoaaeaaoekaaaaappia
abaaoeiaabaaaaacacaaapoaaaaaoeiaafaaaaadaaaaapiaaaaaffjaahaaoeka
aeaaaaaeaaaaapiaagaaoekaaaaaaajaaaaaoeiaaeaaaaaeaaaaapiaaiaaoeka
aaaakkjaaaaaoeiaaeaaaaaeaaaaapiaajaaoekaaaaappjaaaaaoeiaaeaaaaae
aaaaadmaaaaappiaaaaaoekaaaaaoeiaabaaaaacaaaaammaaaaaoeiaabaaaaac
aaaaadoaadaaoejaafaaaaadaaaaahiaabaaffjaalaamjkaaeaaaaaeaaaaahia
akaamjkaabaaaajaaaaaoeiaaeaaaaaeaaaaahiaamaamjkaabaakkjaaaaaoeia
abaaaaacaeaaaboaaaaakkiaafaaaaadabaaahiaacaaffjaalaanckaaeaaaaae
abaaahiaakaanckaacaaaajaabaaoeiaaeaaaaaeabaaahiaamaanckaacaakkja
abaaoeiaafaaaaadacaaahiaaaaaoeiaabaaoeiaaeaaaaaeacaaahiaabaancia
aaaamjiaacaaoeibabaaaaacaeaaacoaacaaaaiaabaaaaacaeaaaeoaabaaffia
abaaaaacafaaaboaaaaaaaiaabaaaaacagaaaboaaaaaffiaabaaaaacafaaacoa
acaaffiaabaaaaacagaaacoaacaakkiaabaaaaacafaaaeoaabaakkiaabaaaaac
agaaaeoaabaaaaiappppaaaafdeieefckiafaaaaeaaaabaagkabaaaafjaaaaae
egiocaaaaaaaaaaabjaaaaaafjaaaaaeegiocaaaabaaaaaaafaaaaaafjaaaaae
egiocaaaacaaaaaabaaaaaaafpaaaaadpcbabaaaaaaaaaaafpaaaaadhcbabaaa
abaaaaaafpaaaaadhcbabaaaacaaaaaafpaaaaaddcbabaaaadaaaaaaghaaaaae
pccabaaaaaaaaaaaabaaaaaagfaaaaaddccabaaaabaaaaaagfaaaaadhccabaaa
acaaaaaagfaaaaadpccabaaaadaaaaaagfaaaaadpccabaaaaeaaaaaagfaaaaad
hccabaaaafaaaaaagfaaaaadhccabaaaagaaaaaagfaaaaadhccabaaaahaaaaaa
giaaaaacadaaaaaadiaaaaaipcaabaaaaaaaaaaafgbfbaaaaaaaaaaaegiocaaa
acaaaaaaabaaaaaadcaaaaakpcaabaaaaaaaaaaaegiocaaaacaaaaaaaaaaaaaa
agbabaaaaaaaaaaaegaobaaaaaaaaaaadcaaaaakpcaabaaaaaaaaaaaegiocaaa
acaaaaaaacaaaaaakgbkbaaaaaaaaaaaegaobaaaaaaaaaaadcaaaaakpccabaaa
aaaaaaaaegiocaaaacaaaaaaadaaaaaapgbpbaaaaaaaaaaaegaobaaaaaaaaaaa
dgaaaaafdccabaaaabaaaaaaegbabaaaadaaaaaadiaaaaaihcaabaaaaaaaaaaa
fgbfbaaaaaaaaaaaegiccaaaacaaaaaaanaaaaaadcaaaaakhcaabaaaaaaaaaaa
egiccaaaacaaaaaaamaaaaaaagbabaaaaaaaaaaaegacbaaaaaaaaaaadcaaaaak
hcaabaaaaaaaaaaaegiccaaaacaaaaaaaoaaaaaakgbkbaaaaaaaaaaaegacbaaa
aaaaaaaadcaaaaakhcaabaaaaaaaaaaaegiccaaaacaaaaaaapaaaaaapgbpbaaa
aaaaaaaaegacbaaaaaaaaaaaaaaaaaajhcaabaaaaaaaaaaaegacbaiaebaaaaaa
aaaaaaaaegiccaaaabaaaaaaaeaaaaaabaaaaaahicaabaaaaaaaaaaaegacbaaa
aaaaaaaaegacbaaaaaaaaaaaeeaaaaaficaabaaaaaaaaaaadkaabaaaaaaaaaaa
diaaaaahhccabaaaacaaaaaapgapbaaaaaaaaaaaegacbaaaaaaaaaaadiaaaaai
pcaabaaaaaaaaaaafgbfbaaaaaaaaaaaegiocaaaacaaaaaaanaaaaaadcaaaaak
pcaabaaaaaaaaaaaegiocaaaacaaaaaaamaaaaaaagbabaaaaaaaaaaaegaobaaa
aaaaaaaadcaaaaakpcaabaaaaaaaaaaaegiocaaaacaaaaaaaoaaaaaakgbkbaaa
aaaaaaaaegaobaaaaaaaaaaadcaaaaakpcaabaaaaaaaaaaaegiocaaaacaaaaaa
apaaaaaapgbpbaaaaaaaaaaaegaobaaaaaaaaaaadgaaaaafpccabaaaadaaaaaa
egaobaaaaaaaaaaadiaaaaaipcaabaaaabaaaaaafgafbaaaaaaaaaaaegiocaaa
aaaaaaaabgaaaaaadcaaaaakpcaabaaaabaaaaaaegiocaaaaaaaaaaabfaaaaaa
agaabaaaaaaaaaaaegaobaaaabaaaaaadcaaaaakpcaabaaaabaaaaaaegiocaaa
aaaaaaaabhaaaaaakgakbaaaaaaaaaaaegaobaaaabaaaaaadcaaaaakpccabaaa
aeaaaaaaegiocaaaaaaaaaaabiaaaaaapgapbaaaaaaaaaaaegaobaaaabaaaaaa
diaaaaaihcaabaaaaaaaaaaafgbfbaaaacaaaaaacgijcaaaacaaaaaaanaaaaaa
dcaaaaakhcaabaaaaaaaaaaacgijcaaaacaaaaaaamaaaaaaagbabaaaacaaaaaa
egacbaaaaaaaaaaadcaaaaakhcaabaaaaaaaaaaacgijcaaaacaaaaaaaoaaaaaa
kgbkbaaaacaaaaaaegacbaaaaaaaaaaadiaaaaaihcaabaaaabaaaaaafgbfbaaa
abaaaaaajgiecaaaacaaaaaaanaaaaaadcaaaaakhcaabaaaabaaaaaajgiecaaa
acaaaaaaamaaaaaaagbabaaaabaaaaaaegacbaaaabaaaaaadcaaaaakhcaabaaa
abaaaaaajgiecaaaacaaaaaaaoaaaaaakgbkbaaaabaaaaaaegacbaaaabaaaaaa
diaaaaahhcaabaaaacaaaaaaegacbaaaaaaaaaaaegacbaaaabaaaaaadcaaaaak
hcaabaaaacaaaaaacgajbaaaaaaaaaaajgaebaaaabaaaaaaegacbaiaebaaaaaa
acaaaaaadgaaaaafcccabaaaafaaaaaaakaabaaaacaaaaaadgaaaaafbccabaaa
afaaaaaackaabaaaabaaaaaadgaaaaafeccabaaaafaaaaaabkaabaaaaaaaaaaa
dgaaaaafbccabaaaagaaaaaaakaabaaaabaaaaaadgaaaaafbccabaaaahaaaaaa
bkaabaaaabaaaaaadgaaaaafeccabaaaagaaaaaackaabaaaaaaaaaaadgaaaaaf
eccabaaaahaaaaaaakaabaaaaaaaaaaadgaaaaafcccabaaaagaaaaaabkaabaaa
acaaaaaadgaaaaafcccabaaaahaaaaaackaabaaaacaaaaaadoaaaaabejfdeheo
kiaaaaaaafaaaaaaaiaaaaaaiaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaaaaaaaaa
apapaaaaijaaaaaaaaaaaaaaaaaaaaaaadaaaaaaabaaaaaaapahaaaajbaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaacaaaaaaahahaaaajiaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaadaaaaaaapadaaaakbaaaaaaaaaaaaaaaaaaaaaaadaaaaaaaeaaaaaa
apaaaaaafaepfdejfeejepeoaafeebeoehefeofeaaeoepfcenebemaafeeffied
epepfceeaaedepemepfcaaklepfdeheooaaaaaaaaiaaaaaaaiaaaaaamiaaaaaa
aaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaaneaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaadamaaaaneaaaaaaabaaaaaaaaaaaaaaadaaaaaaacaaaaaa
ahaiaaaaneaaaaaaacaaaaaaaaaaaaaaadaaaaaaadaaaaaaapaaaaaaneaaaaaa
adaaaaaaaaaaaaaaadaaaaaaaeaaaaaaapaaaaaaneaaaaaaaeaaaaaaaaaaaaaa
adaaaaaaafaaaaaaahaiaaaaneaaaaaaafaaaaaaaaaaaaaaadaaaaaaagaaaaaa
ahaiaaaaneaaaaaaagaaaaaaaaaaaaaaadaaaaaaahaaaaaaahaiaaaafdfgfpfa
epfdejfeejepeoaafeeffiedepepfceeaaklklkl"
}
}
Program "fp" {
// Platform opengl skipped due to earlier errors
// Platform d3d9 skipped due to earlier errors
// Platform opengl had shader errors
//   <no keywords>
// Platform d3d9 had shader errors
//   <no keywords>
// Platform d3d11_9x had shader errors
//   <no keywords>
SubProgram "d3d11 " {
// Stats: 114 math, 12 textures, 4 branches
SetTexture 0 [_BumpMap] 2D 1
SetTexture 1 [_RoughnessMap] 2D 3
SetTexture 2 [_LightTextureB0] 2D 11
SetTexture 3 [_LightTexture0] 2D 10
SetTexture 4 [_FresnelMap] 2D 6
SetTexture 5 [_SpecularMap] 2D 2
SetTexture 6 [_MainTex] 2D 0
SetTexture 7 [_MetalnessMap] 2D 7
SetTexture 8 [_AOMap] 2D 8
SetTexture 9 [_Reflection] CUBE 9
SetTexture 10 [_RimMap] 2D 4
SetTexture 11 [_TranslucentMap] 2D 5
ConstBuffer "$Globals" 400
Matrix 336 [_LightMatrix0]
Vector 0 [_Color]
Float 32 [_Roughness]
Float 36 [_F0]
Vector 48 [_RimColor]
Float 64 [_RimPower]
Float 68 [_RimShift]
Vector 80 [_TranslucentColor]
Float 96 [_TranslucentPower]
Float 100 [_TranslucentTilt]
Vector 112 [_SpecularColor] 3
Float 124 [_Metalness]
Vector 128 [_BumpMap_ST]
Float 144 [_BumpScale]
Vector 160 [_SpecularMap_ST]
Vector 176 [_RoughnessMap_ST]
Vector 192 [_RimMap_ST]
Vector 208 [_TranslucentMap_ST]
Vector 224 [_FresnelMap_ST]
Vector 240 [_MetalnessMap_ST]
Vector 256 [_AOMap_ST]
Float 272 [_LambertScale]
Float 276 [_LambertOffset]
Vector 304 [_LightColor0]
ConstBuffer "UnityLighting" 720
Vector 0 [_WorldSpaceLightPos0]
BindCB  "$Globals" 0
BindCB  "UnityLighting" 1
"ps_4_0
eefiecedakhfmhpapfeogfikdogmcjjmejloibdhabaaaaaaimbdaaaaadaaaaaa
cmaaaaaabeabaaaaeiabaaaaejfdeheooaaaaaaaaiaaaaaaaiaaaaaamiaaaaaa
aaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaaneaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaadadaaaaneaaaaaaabaaaaaaaaaaaaaaadaaaaaaacaaaaaa
ahahaaaaneaaaaaaacaaaaaaaaaaaaaaadaaaaaaadaaaaaaapahaaaaneaaaaaa
adaaaaaaaaaaaaaaadaaaaaaaeaaaaaaapapaaaaneaaaaaaaeaaaaaaaaaaaaaa
adaaaaaaafaaaaaaahahaaaaneaaaaaaafaaaaaaaaaaaaaaadaaaaaaagaaaaaa
ahahaaaaneaaaaaaagaaaaaaaaaaaaaaadaaaaaaahaaaaaaahahaaaafdfgfpfa
epfdejfeejepeoaafeeffiedepepfceeaaklklklepfdeheocmaaaaaaabaaaaaa
aiaaaaaacaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapaaaaaafdfgfpfe
gbhcghgfheaaklklfdeieefcdmbcaaaaeaaaaaaaipaeaaaafjaaaaaeegiocaaa
aaaaaaaabjaaaaaafjaaaaaeegiocaaaabaaaaaaabaaaaaafkaaaaadaagabaaa
aaaaaaaafkaaaaadaagabaaaabaaaaaafkaaaaadaagabaaaacaaaaaafkaaaaad
aagabaaaadaaaaaafkaaaaadaagabaaaaeaaaaaafkaaaaadaagabaaaafaaaaaa
fkaaaaadaagabaaaagaaaaaafkaaaaadaagabaaaahaaaaaafkaaaaadaagabaaa
aiaaaaaafkaaaaadaagabaaaajaaaaaafkaaaaadaagabaaaakaaaaaafkaaaaad
aagabaaaalaaaaaafibiaaaeaahabaaaaaaaaaaaffffaaaafibiaaaeaahabaaa
abaaaaaaffffaaaafibiaaaeaahabaaaacaaaaaaffffaaaafibiaaaeaahabaaa
adaaaaaaffffaaaafibiaaaeaahabaaaaeaaaaaaffffaaaafibiaaaeaahabaaa
afaaaaaaffffaaaafibiaaaeaahabaaaagaaaaaaffffaaaafibiaaaeaahabaaa
ahaaaaaaffffaaaafibiaaaeaahabaaaaiaaaaaaffffaaaafidaaaaeaahabaaa
ajaaaaaaffffaaaafibiaaaeaahabaaaakaaaaaaffffaaaafibiaaaeaahabaaa
alaaaaaaffffaaaagcbaaaaddcbabaaaabaaaaaagcbaaaadhcbabaaaacaaaaaa
gcbaaaadhcbabaaaadaaaaaagcbaaaadpcbabaaaaeaaaaaagcbaaaadhcbabaaa
afaaaaaagcbaaaadhcbabaaaagaaaaaagcbaaaadhcbabaaaahaaaaaagfaaaaad
pccabaaaaaaaaaaagiaaaaacalaaaaaabaaaaaahbcaabaaaaaaaaaaaegbcbaaa
acaaaaaaegbcbaaaacaaaaaaeeaaaaafbcaabaaaaaaaaaaaakaabaaaaaaaaaaa
diaaaaahocaabaaaaaaaaaaaagaabaaaaaaaaaaaagbjbaaaacaaaaaadcaaaaal
dcaabaaaabaaaaaaegbabaaaabaaaaaaegiacaaaaaaaaaaaaiaaaaaaogikcaaa
aaaaaaaaaiaaaaaaefaaaaajpcaabaaaabaaaaaaegaabaaaabaaaaaaeghobaaa
aaaaaaaaaagabaaaabaaaaaadgaaaaagbcaabaaaacaaaaaaakiacaaaaaaaaaaa
ajaaaaaadgaaaaafecaabaaaacaaaaaaabeaaaaaaaaaiadpdiaaaaahhcaabaaa
abaaaaaaegacbaaaabaaaaaaagacbaaaacaaaaaabaaaaaahbcaabaaaacaaaaaa
egbcbaaaafaaaaaaegacbaaaabaaaaaabaaaaaahccaabaaaacaaaaaaegbcbaaa
agaaaaaaegacbaaaabaaaaaabaaaaaahecaabaaaacaaaaaaegbcbaaaahaaaaaa
egacbaaaabaaaaaabaaaaaahbcaabaaaabaaaaaaegacbaaaacaaaaaaegacbaaa
acaaaaaaeeaaaaafbcaabaaaabaaaaaaakaabaaaabaaaaaadiaaaaahhcaabaaa
abaaaaaaagaabaaaabaaaaaaegacbaaaacaaaaaadcaaaaaldcaabaaaacaaaaaa
egbabaaaabaaaaaaegiacaaaaaaaaaaaalaaaaaaogikcaaaaaaaaaaaalaaaaaa
efaaaaajpcaabaaaacaaaaaaegaabaaaacaaaaaaeghobaaaabaaaaaaaagabaaa
adaaaaaadiaaaaaiicaabaaaabaaaaaaakaabaaaacaaaaaaakiacaaaaaaaaaaa
acaaaaaabiaaaaaibcaabaaaacaaaaaadkiacaaaabaaaaaaaaaaaaaaabeaaaaa
aaaaaaaabpaaaeadakaabaaaacaaaaaabaaaaaajbcaabaaaacaaaaaaegiccaaa
abaaaaaaaaaaaaaaegiccaaaabaaaaaaaaaaaaaaeeaaaaafbcaabaaaacaaaaaa
akaabaaaacaaaaaadiaaaaaihcaabaaaacaaaaaaagaabaaaacaaaaaaegiccaaa
abaaaaaaaaaaaaaadgaaaaafbcaabaaaadaaaaaaabeaaaaaaaaaiadpbcaaaaab
aaaaaaajhcaabaaaaeaaaaaaegbcbaiaebaaaaaaadaaaaaaegiccaaaabaaaaaa
aaaaaaaadjaaaaaiicaabaaaacaaaaaadkiacaaaaaaaaaaabiaaaaaaabeaaaaa
aaaaiadpbpaaaeaddkaabaaaacaaaaaabaaaaaahicaabaaaacaaaaaaegbcbaaa
aeaaaaaaegbcbaaaaeaaaaaaefaaaaajpcaabaaaafaaaaaapgapbaaaacaaaaaa
eghobaaaacaaaaaaaagabaaaalaaaaaaaoaaaaahgcaabaaaafaaaaaaagbbbaaa
aeaaaaaapgbpbaaaaeaaaaaaaaaaaaakgcaabaaaafaaaaaafgagbaaaafaaaaaa
aceaaaaaaaaaaaaaaaaaaadpaaaaaadpaaaaaaaaefaaaaajpcaabaaaagaaaaaa
jgafbaaaafaaaaaaeghobaaaadaaaaaaaagabaaaakaaaaaadbaaaaahicaabaaa
acaaaaaaabeaaaaaaaaaaaaackbabaaaaeaaaaaaabaaaaahicaabaaaacaaaaaa
dkaabaaaacaaaaaaabeaaaaaaaaaiadpdiaaaaahicaabaaaacaaaaaadkaabaaa
agaaaaaadkaabaaaacaaaaaadiaaaaahbcaabaaaadaaaaaaakaabaaaafaaaaaa
dkaabaaaacaaaaaabcaaaaabbaaaaaahicaabaaaacaaaaaaegbcbaaaaeaaaaaa
egbcbaaaaeaaaaaaefaaaaajpcaabaaaadaaaaaapgapbaaaacaaaaaaeghobaaa
adaaaaaaaagabaaaakaaaaaabfaaaaabbaaaaaahicaabaaaacaaaaaaegacbaaa
aeaaaaaaegacbaaaaeaaaaaaeeaaaaaficaabaaaacaaaaaadkaabaaaacaaaaaa
diaaaaahhcaabaaaacaaaaaapgapbaaaacaaaaaaegacbaaaaeaaaaaabfaaaaab
dcaaaaajocaabaaaadaaaaaaagbjbaaaacaaaaaaagaabaaaaaaaaaaaagajbaaa
acaaaaaabaaaaaahbcaabaaaaaaaaaaajgahbaaaadaaaaaajgahbaaaadaaaaaa
eeaaaaafbcaabaaaaaaaaaaaakaabaaaaaaaaaaadiaaaaahocaabaaaadaaaaaa
agaabaaaaaaaaaaafgaobaaaadaaaaaabaaaaaaibcaabaaaaaaaaaaajgahbaia
ebaaaaaaaaaaaaaaegacbaaaabaaaaaaaaaaaaahbcaabaaaaaaaaaaaakaabaaa
aaaaaaaaakaabaaaaaaaaaaadcaaaaalhcaabaaaaeaaaaaaegacbaaaabaaaaaa
agaabaiaebaaaaaaaaaaaaaajgahbaiaebaaaaaaaaaaaaaabacaaaahbcaabaaa
aaaaaaaaegacbaaaacaaaaaaegacbaaaabaaaaaabacaaaahicaabaaaacaaaaaa
egacbaaaacaaaaaajgahbaaaadaaaaaabacaaaahbcaabaaaacaaaaaaegacbaaa
acaaaaaaegacbaaaaeaaaaaabacaaaahccaabaaaaaaaaaaajgahbaaaaaaaaaaa
egacbaaaabaaaaaabacaaaahecaabaaaaaaaaaaajgahbaaaadaaaaaaegacbaaa
abaaaaaaaaaaaaaiicaabaaaaaaaaaaabkaabaiaebaaaaaaaaaaaaaaabeaaaaa
aaaaiadpaacaaaaiicaabaaaaaaaaaaadkaabaaaaaaaaaaabkiacaaaaaaaaaaa
aeaaaaaadccaaaalccaabaaaacaaaaaaakaabaaaaaaaaaaaakiacaaaaaaaaaaa
bbaaaaaabkiacaaaaaaaaaaabbaaaaaadcaaaaalgcaabaaaadaaaaaaagbbbaaa
abaaaaaaagibcaaaaaaaaaaaaoaaaaaakgilcaaaaaaaaaaaaoaaaaaaefaaaaaj
pcaabaaaafaaaaaajgafbaaaadaaaaaaeghobaaaaeaaaaaaaagabaaaagaaaaaa
diaaaaaiecaabaaaacaaaaaaakaabaaaafaaaaaabkiacaaaaaaaaaaaacaaaaaa
dcaaaaalccaabaaaadaaaaaabkiacaiaebaaaaaaaaaaaaaaacaaaaaaakaabaaa
afaaaaaaabeaaaaaaaaaiadpaaaaaaaiicaabaaaacaaaaaadkaabaiaebaaaaaa
acaaaaaaabeaaaaaaaaaiadpdiaaaaahecaabaaaadaaaaaadkaabaaaacaaaaaa
dkaabaaaacaaaaaadiaaaaahecaabaaaadaaaaaackaabaaaadaaaaaackaabaaa
adaaaaaadiaaaaahicaabaaaacaaaaaadkaabaaaacaaaaaackaabaaaadaaaaaa
dcaaaaajecaabaaaacaaaaaabkaabaaaadaaaaaadkaabaaaacaaaaaackaabaaa
acaaaaaadiaaaaaihcaabaaaadaaaaaaagaabaaaadaaaaaaegiccaaaaaaaaaaa
bdaaaaaadiaaaaahicaabaaaacaaaaaadkaabaaaabaaaaaadkaabaaaabaaaaaa
diaaaaahicaabaaaadaaaaaadkaabaaaacaaaaaadkaabaaaacaaaaaadiaaaaah
ecaabaaaaaaaaaaackaabaaaaaaaaaaackaabaaaaaaaaaaadcaaaaajicaabaaa
aeaaaaaadkaabaaaacaaaaaadkaabaaaacaaaaaaabeaaaaaaaaaialpdcaaaaaj
ecaabaaaaaaaaaaackaabaaaaaaaaaaadkaabaaaaeaaaaaaabeaaaaaaaaaiadp
diaaaaahecaabaaaaaaaaaaackaabaaaaaaaaaaackaabaaaaaaaaaaadiaaaaah
ecaabaaaaaaaaaaackaabaaaaaaaaaaaabeaaaaanaapejeaaoaaaaahecaabaaa
aaaaaaaadkaabaaaadaaaaaackaabaaaaaaaaaaadiaaaaahicaabaaaadaaaaaa
dkaabaaaacaaaaaaabeaaaaaaaaaaadpdcaaaaakicaabaaaacaaaaaadkaabaia
ebaaaaaaacaaaaaaabeaaaaaaaaaaadpabeaaaaaaaaaiadpdcaaaaajicaabaaa
aeaaaaaaakaabaaaaaaaaaaadkaabaaaacaaaaaadkaabaaaadaaaaaaaoaaaaak
icaabaaaaeaaaaaaaceaaaaaaaaaiadpaaaaiadpaaaaiadpaaaaiadpdkaabaaa
aeaaaaaadcaaaaajicaabaaaacaaaaaabkaabaaaaaaaaaaadkaabaaaacaaaaaa
dkaabaaaadaaaaaaaoaaaaakicaabaaaacaaaaaaaceaaaaaaaaaiadpaaaaiadp
aaaaiadpaaaaiadpdkaabaaaacaaaaaadiaaaaahicaabaaaacaaaaaadkaabaaa
acaaaaaadkaabaaaaeaaaaaadiaaaaahbcaabaaaaaaaaaaackaabaaaaaaaaaaa
akaabaaaaaaaaaaadiaaaaahbcaabaaaaaaaaaaackaabaaaacaaaaaaakaabaaa
aaaaaaaadicaaaahbcaabaaaaaaaaaaadkaabaaaacaaaaaaakaabaaaaaaaaaaa
dcaaaaaldcaabaaaafaaaaaaegbabaaaabaaaaaaegiacaaaaaaaaaaaakaaaaaa
ogikcaaaaaaaaaaaakaaaaaaefaaaaajpcaabaaaafaaaaaaegaabaaaafaaaaaa
eghobaaaafaaaaaaaagabaaaacaaaaaadiaaaaaihcaabaaaafaaaaaaegacbaaa
afaaaaaaegiccaaaaaaaaaaaahaaaaaadiaaaaahhcaabaaaafaaaaaaagaabaaa
aaaaaaaaegacbaaaafaaaaaadiaaaaahhcaabaaaagaaaaaaegacbaaaadaaaaaa
egacbaaaafaaaaaaefaaaaajpcaabaaaahaaaaaaegbabaaaabaaaaaaeghobaaa
agaaaaaaaagabaaaaaaaaaaadiaaaaaipcaabaaaahaaaaaaegaobaaaahaaaaaa
egiocaaaaaaaaaaaaaaaaaaadcaaaaalfcaabaaaaaaaaaaaagbbbaaaabaaaaaa
agibcaaaaaaaaaaaapaaaaaakgilcaaaaaaaaaaaapaaaaaaefaaaaajpcaabaaa
aiaaaaaaigaabaaaaaaaaaaaeghobaaaahaaaaaaaagabaaaahaaaaaadiaaaaai
bcaabaaaaaaaaaaaakaabaaaaiaaaaaadkiacaaaaaaaaaaaahaaaaaadcaaaaal
dcaabaaaaiaaaaaaegbabaaaabaaaaaaegiacaaaaaaaaaaabaaaaaaaogikcaaa
aaaaaaaabaaaaaaaefaaaaajpcaabaaaaiaaaaaaegaabaaaaiaaaaaaeghobaaa
aiaaaaaaaagabaaaaiaaaaaaeiaaaaalpcaabaaaajaaaaaaegacbaaaabaaaaaa
eghobaaaajaaaaaaaagabaaaajaaaaaaabeaaaaaaaaaiaebdiaaaaahhcaabaaa
abaaaaaaegacbaaaadaaaaaaegacbaaaajaaaaaadcaaaaalgcaabaaaaiaaaaaa
agbbbaaaabaaaaaaagibcaaaaaaaaaaaamaaaaaakgilcaaaaaaaaaaaamaaaaaa
efaaaaajpcaabaaaajaaaaaajgafbaaaaiaaaaaaeghobaaaakaaaaaaaagabaaa
aeaaaaaadcaaaaalgcaabaaaaiaaaaaaagbbbaaaabaaaaaaagibcaaaaaaaaaaa
anaaaaaakgilcaaaaaaaaaaaanaaaaaaefaaaaajpcaabaaaakaaaaaajgafbaaa
aiaaaaaaeghobaaaalaaaaaaaagabaaaafaaaaaadiaaaaaiocaabaaaaiaaaaaa
agajbaaaajaaaaaaagijcaaaaaaaaaaaadaaaaaacpaaaaafecaabaaaaaaaaaaa
dkaabaaaaaaaaaaadiaaaaaiecaabaaaaaaaaaaackaabaaaaaaaaaaaakiacaaa
aaaaaaaaaeaaaaaabjaaaaafecaabaaaaaaaaaaackaabaaaaaaaaaaadiaaaaah
ocaabaaaaiaaaaaakgakbaaaaaaaaaaafgaobaaaaiaaaaaadiaaaaahocaabaaa
aiaaaaaakgakbaaaacaaaaaafgaobaaaaiaaaaaadcaaaaamhcaabaaaajaaaaaa
egiccaaaaaaaaaaaafaaaaaaegacbaaaahaaaaaaegiccaiaebaaaaaaaaaaaaaa
afaaaaaadcaaaaalhcaabaaaajaaaaaafgifcaaaaaaaaaaaagaaaaaaegacbaaa
ajaaaaaaegiccaaaaaaaaaaaafaaaaaadiaaaaahhcaabaaaajaaaaaaegacbaaa
ajaaaaaaegacbaaaakaaaaaacpaaaaafccaabaaaaaaaaaaabkaabaaaaaaaaaaa
diaaaaaiccaabaaaaaaaaaaabkaabaaaaaaaaaaaakiacaaaaaaaaaaaagaaaaaa
bjaaaaafccaabaaaaaaaaaaabkaabaaaaaaaaaaadiaaaaahocaabaaaaaaaaaaa
fgafbaaaaaaaaaaaagajbaaaajaaaaaadeaaaaahocaabaaaaaaaaaaafgaobaaa
aaaaaaaafgaobaaaaiaaaaaadiaaaaahocaabaaaaaaaaaaaagajbaaaadaaaaaa
fgaobaaaaaaaaaaadiaaaaahecaabaaaacaaaaaadkaabaaaabaaaaaaabeaaaaa
aaaahaebeiaaaaalpcaabaaaaeaaaaaaegacbaaaaeaaaaaaeghobaaaajaaaaaa
aagabaaaajaaaaaackaabaaaacaaaaaadcaaaaajicaabaaaabaaaaaadkaabaaa
abaaaaaaabeaaaaaaaaamgecabeaaaaaaaaaiadpaoaaaaahicaabaaaabaaaaaa
abeaaaaaaaaamiecdkaabaaaabaaaaaacpaaaaafbcaabaaaacaaaaaaakaabaaa
acaaaaaadiaaaaahicaabaaaabaaaaaadkaabaaaabaaaaaaakaabaaaacaaaaaa
bjaaaaaficaabaaaabaaaaaadkaabaaaabaaaaaadeaaaaahncaabaaaacaaaaaa
pgapbaaaabaaaaaaagajbaaaaeaaaaaadiaaaaaincaabaaaacaaaaaaagaobaaa
acaaaaaaagijcaaaaaaaaaaaahaaaaaadiaaaaahhcaabaaaaeaaaaaafgafbaaa
acaaaaaaegacbaaaadaaaaaadeaaaaahhcaabaaaabaaaaaaegacbaaaabaaaaaa
egacbaaaaeaaaaaadcaaaaajocaabaaaaaaaaaaaagajbaaaahaaaaaaagajbaaa
abaaaaaafgaobaaaaaaaaaaadcaaaaajocaabaaaaaaaaaaaagajbaaaafaaaaaa
agajbaaaadaaaaaafgaobaaaaaaaaaaadcaaaaajhcaabaaaabaaaaaaigadbaaa
acaaaaaaegacbaaaadaaaaaaegacbaaaagaaaaaaaaaaaaaihcaabaaaabaaaaaa
jgahbaiaebaaaaaaaaaaaaaaegacbaaaabaaaaaadcaaaaajhcaabaaaaaaaaaaa
agaabaaaaaaaaaaaegacbaaaabaaaaaajgahbaaaaaaaaaaadiaaaaahhccabaaa
aaaaaaaaagaabaaaaiaaaaaaegacbaaaaaaaaaaadgaaaaaficcabaaaaaaaaaaa
dkaabaaaahaaaaaadoaaaaab"
}
}
 }
}
Fallback "Diffuse"
}